# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: '#about'
    weight: 10
    
    
  - name: Publications
    url: '#publications'
    weight: 15

  - name: Python & R Guides
    url: how-to-guides/
    weight: 20
    
#  - name: Projects
#    url: '#projects'
#    weight: 20
    
#  - name: Posts
#    url: '#posts'
#    weight: 30
    
# - name: Courses
#    url: '#courses'
#    weight: 25
    
#  - name: Contact
#    url: '#contact'
#    weight: 70
